# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Regra')),
                ('tipo_regra', models.CharField(choices=[('percentual', 'Percentual Simples'), ('gatilho_percentual', 'Gatilho + Percentual'), ('gatilho_valor_fixo', 'Gatilho + Valor Fixo')], max_length=50, verbose_name='Tipo de Regra')),
                ('campo_valor', models.CharField(choices=[('valor_af', 'Valor AF'), ('valor_repasse', 'Valor Repasse')], default='valor_af', max_length=20, verbose_name='Campo de Valor')),
                ('percentual_padrao', models.DecimalField(blank=True, decimal_places=2, help_text='Usado apenas quando a regra é Percentual sem gatilho', max_digits=5, null=True, verbose_name='Percentual Padrão (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Regra de Bonificação',
                'verbose_name_plural': 'Regras de Bonificação',
                'ordering': ['-ativo', '-data_criacao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ReducaoBonificacaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Ex: 20 = reduzir 20% do valor atual', max_digits=6, verbose_name='Percentual de Redução (%)')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Regra de Redução (Bonificação)',
                'verbose_name_plural': 'Regras de Redução (Bonificação)',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='BonificacaoGatilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Valor mínimo da faixa para ativar este gatilho', max_digits=14, verbose_name='Valor Mínimo')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Usado apenas para regras do tipo Gatilho + Valor Fixo', max_digits=14, null=True, verbose_name='Valor Fixo (R$)')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Usado apenas para regras do tipo Gatilho + Percentual', max_digits=5, null=True, verbose_name='Percentual (%)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatilhos', to='bonificacoes.bonificacaoregra', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Gatilho de Bonificação',
                'verbose_name_plural': 'Gatilhos de Bonificação',
                'ordering': ['valor_minimo'],
            },
        ),
        migrations.CreateModel(
            name='BonificacaoFuncionarioRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Maior prioridade = primeiro na ordem de aplicação (1º)', verbose_name='Prioridade')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_bonificacao', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='bonificacoes.bonificacaoregra', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Vínculo Funcionário-Regra',
                'verbose_name_plural': 'Vínculos Funcionário-Regra',
                'ordering': ['-prioridade', 'regra__nome'],
                'unique_together': {('funcionario', 'regra')},
            },
        ),
        migrations.CreateModel(
            name='ReducaoBonificacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(help_text='Data em que a ocorrência aconteceu (usado para filtrar no período)', verbose_name='Data do Evento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reducoes_bonificacao', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('regra_reducao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='bonificacoes.reducaobonificacaoregra', verbose_name='Regra de Redução')),
            ],
            options={
                'verbose_name': 'Redução aplicada ao Funcionário',
                'verbose_name_plural': 'Reduções aplicadas aos Funcionários',
                'ordering': ['regra_reducao__ordem', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='BonificacaoCalculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Período Início')),
                ('periodo_fim', models.DateField(verbose_name='Período Fim')),
                ('valor_base', models.DecimalField(decimal_places=2, help_text='Valor total encontrado no período', max_digits=14, verbose_name='Valor Base')),
                ('valor_bonificacao', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor da Bonificação')),
                ('valor_bonificacao_final', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da bonificação após aplicar reduções (se houver)', max_digits=14, null=True, verbose_name='Valor da Bonificação (Final)')),
                ('reducoes_aplicadas', models.JSONField(blank=True, null=True, verbose_name='Reduções Aplicadas (JSON)')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificacoes_calculadas', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('gatilho_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_aplicados', to='bonificacoes.bonificacaogatilho', verbose_name='Gatilho Aplicado')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos', to='bonificacoes.bonificacaoregra', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Bonificação Calculada',
                'verbose_name_plural': 'Bonificações Calculadas',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.AddIndex(
            model_name='reducaobonificacaofuncionario',
            index=models.Index(fields=['funcionario', 'data_evento'], name='bonificacoes_funcion_8a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='reducaobonificacaofuncionario',
            index=models.Index(fields=['regra_reducao', 'data_criacao'], name='bonificacoes_regra_r_9d4e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='bonificacaocalculada',
            index=models.Index(fields=['funcionario', 'periodo_inicio', 'periodo_fim'], name='bonificacoes_funcion_1a2b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='bonificacaocalculada',
            index=models.Index(fields=['regra', 'data_calculo'], name='bonificacoes_regra__4d5e6f_idx'),
        ),
    ]
