# Generated by Django 6.0 on 2026-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonificacaoregra',
            name='campo_valor',
            field=models.CharField(choices=[('valor_af', 'Valor AF'), ('valor_repasse', 'Valor Repasse')], default='valor_repasse', max_length=20, verbose_name='Campo de Valor'),
        ),
    ]
