# Generated by Django 6.0 on 2026-02-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_geral', '0001_initial'),
        ('funcionarios', '0002_funcionario_chave_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios_tesouraria', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios', to='financeiro_geral.tipobeneficio', verbose_name='Tipo de Benefício')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['-data_vencimento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro_geral.categoriaconta', verbose_name='Categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro_geral.subcategoriaconta', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Conta (empresa)',
                'verbose_name_plural': 'Contas (empresa)',
                'ordering': ['-data_vencimento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios_tesouraria', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Salário',
                'verbose_name_plural': 'Salários',
                'ordering': ['-data_vencimento', '-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='ContaPagar',
        ),
    ]
