# Generated by Django 6.0 on 2026-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_geral', '0002_beneficio_conta_salario_delete_contapagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='tesouraria/comprovantes/%Y/%m/', verbose_name='Comprovante de pagamento'),
        ),
        migrations.AddField(
            model_name='conta',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='tesouraria/comprovantes/%Y/%m/', verbose_name='Comprovante de pagamento'),
        ),
        migrations.AddField(
            model_name='salario',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='tesouraria/comprovantes/%Y/%m/', verbose_name='Comprovante de pagamento'),
        ),
    ]
