# Generated by Django 6.0 on 2026-03-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_geral', '0003_beneficio_comprovante_conta_comprovante_and_more'),
        ('funcionarios', '0002_funcionario_chave_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonificacaoAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bonificacao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Bonificação (R$)')),
                ('mes_referente', models.CharField(max_length=20, verbose_name='Mês Referente')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='tesouraria/comprovantes/%Y/%m/', verbose_name='Comprovante de pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status_pagamento', models.BooleanField(default=False, verbose_name='Pago')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonificacoes_a_pagar', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Bonificação a Pagar',
                'verbose_name_plural': 'Bonificações a Pagar',
                'ordering': ['status_pagamento', '-data_criacao', 'funcionario__nome_completo'],
            },
        ),
    ]
