# Generated by Django 6.0 on 2026-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_geral', '0004_bonificacaoapagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonificacaoapagar',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
    ]
