# Generated by Django 6.0 on 2026-01-13 17:38

import apps.rh.ponto.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_funcionario_chave_pix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHorarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalha_fim_semana', models.BooleanField(default=False, verbose_name='Trabalha em Fins de Semana')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias da semana que trabalha', verbose_name='Dias da Semana')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_horario', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('horario_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_funcionarios', to='funcionarios.horariotrabalho', verbose_name='Horário de Trabalho')),
            ],
            options={
                'verbose_name': 'Configuração de Horário do Funcionário',
                'verbose_name_plural': 'Configurações de Horário dos Funcionários',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('ABONO', 'Abono'), ('ATESTADO', 'Atestado'), ('FERIADO', 'Feriado')], max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Null para justificativas em lote', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='JustificativaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.rh.ponto.models.get_justificativa_upload_path, verbose_name='Arquivo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('justificativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='ponto.justificativa', verbose_name='Justificativa')),
            ],
            options={
                'verbose_name': 'Arquivo de Justificativa',
                'verbose_name_plural': 'Arquivos de Justificativas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('numero', models.IntegerField(help_text='1 ou 2 - primeira ou segunda entrada/saída', verbose_name='Número')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('data', models.DateField(help_text='Apenas a data, para facilitar consultas', verbose_name='Data')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data', '-data_hora'],
                'unique_together': {('funcionario', 'data', 'tipo', 'numero')},
            },
        ),
    ]
