# Generated by Django 6.0 on 2026-01-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_chave_pix'),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaohorariofuncionario',
            name='dias_semana',
        ),
        migrations.AddField(
            model_name='configuracaohorariofuncionario',
            name='horarios_por_dia',
            field=models.JSONField(default=dict, help_text='JSON com horários específicos para cada dia da semana', verbose_name='Horários por Dia'),
        ),
        migrations.AlterField(
            model_name='configuracaohorariofuncionario',
            name='horario_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_funcionarios', to='funcionarios.horariotrabalho', verbose_name='Horário de Trabalho Padrão'),
        ),
    ]
