# Generated by Django 6.0 on 2025-12-17 19:52

import apps.geral.comunicados.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('cor', models.CharField(default='#FFD700', help_text='Cor em hexadecimal (ex: #FFD700)', max_length=7, verbose_name='Cor da Categoria')),
                ('icone', models.CharField(default='bx-message-square-detail', help_text='Classe do ícone Boxicons (ex: bx-message-square-detail)', max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (0 = maior prioridade)', verbose_name='Ordem')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria de Comunicado',
                'verbose_name_plural': 'Categorias de Comunicados',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('AVISO', 'Aviso'), ('ATUALIZACAO', 'Atualização do Sistema'), ('EVENTO_FUTURO', 'Evento Futuro'), ('EVENTO_PASSADO', 'Evento Passado'), ('TAREFA', 'Tarefa/Coisa a Fazer'), ('GERAL', 'Geral')], default='GERAL', max_length=20, verbose_name='Tipo de Comunicado')),
                ('conteudo', models.TextField(help_text='Texto do comunicado', verbose_name='Conteúdo')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.geral.comunicados.models.get_comunicado_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Banner')),
                ('data_evento', models.DateTimeField(blank=True, help_text='Data do evento (para eventos futuros ou passados)', null=True, verbose_name='Data do Evento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('fixo', models.BooleanField(default=False, help_text='Se marcado, o comunicado ficará sempre no topo do mural', verbose_name='Fixo no Topo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='comunicados.categoriacomunicado', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fixo', '-prioridade', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.geral.comunicados.models.get_comunicado_upload_path, verbose_name='Arquivo')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Arquivo')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='comunicados.comunicado', verbose_name='Comunicado')),
            ],
            options={
                'verbose_name': 'Arquivo de Comunicado',
                'verbose_name_plural': 'Arquivos de Comunicados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacaoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False, verbose_name='Visualizado')),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Visualização')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='comunicados.comunicado', verbose_name='Comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_visualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visualização de Comunicado',
                'verbose_name_plural': 'Visualizações de Comunicados',
                'ordering': ['-data_visualizacao'],
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
