# Generated by Django 6.0 on 2025-12-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('CT', 'Categoria - APP (Menu Lateral)'), ('SCT', 'SubCategoria - Render/Template/URL'), ('SS', 'Sessão - Section/Container'), ('SSS', 'SubSessão - Div/Content'), ('CX', 'Caixa - div/span/box/card')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GroupsAcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('acessos', models.ManyToManyField(related_name='groups_acessos', to='permissoes.acesso', verbose_name='Acessos')),
            ],
            options={
                'verbose_name': 'Grupo de Acessos',
                'verbose_name_plural': 'Grupos de Acessos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='AcessoHierarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('filhos', models.ManyToManyField(help_text='Acessos que serão filhos deste pai (ex: SCTs para CT, SSs para SCT)', related_name='hierarquias_como_filho', to='permissoes.acesso', verbose_name='Acessos Filhos')),
                ('pai', models.ForeignKey(help_text='Acesso que será o pai (ex: CT, SCT)', on_delete=django.db.models.deletion.CASCADE, related_name='hierarquias_como_pai', to='permissoes.acesso', verbose_name='Acesso Pai')),
            ],
            options={
                'verbose_name': 'Hierarquia de Acesso',
                'verbose_name_plural': 'Hierarquias de Acessos',
                'ordering': ['pai__nome'],
                'unique_together': {('pai',)},
            },
        ),
        migrations.CreateModel(
            name='ControleAcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('acessos', models.ManyToManyField(related_name='usuarios_controle', to='permissoes.acesso', verbose_name='Acessos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_acessos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Controle de Acesso',
                'verbose_name_plural': 'Controles de Acesso',
                'ordering': ['user__username'],
                'unique_together': {('user',)},
            },
        ),
    ]
