# Migração inicial do app contratos_v2 (tabelas contratos_v2_* no MySQL).

import django.db.models.deletion
import django.db.models.functions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siape', '0005_carteira_operacional_contratos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=120, null=True, verbose_name='Naturalidade')),
                ('pais_origem', models.CharField(blank=True, max_length=80, null=True, verbose_name='País de origem')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CPF')),
                ('numero_rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número RG')),
                ('orgao_emissor_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão emissor RG')),
                ('uf_emissao_rg', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF emissão RG')),
                ('data_emissao_rg', models.DateField(blank=True, null=True, verbose_name='Data emissão RG')),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do pai')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da mãe')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Cliente — dados pessoais',
                'verbose_name_plural': 'Cliente — dados pessoais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código')),
                ('ispb', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISPB')),
                ('nome_curto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome curto')),
                ('dominio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Domínio oficial')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL do logo (remoto)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bancos/logos/', verbose_name='Logo (cache local)')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banco (catálogo contratos)',
                'verbose_name_plural': 'Bancos (catálogo contratos)',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Convênio (catálogo contratos)',
                'verbose_name_plural': 'Convênios (catálogo contratos)',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('flag_port_mais_refin', models.BooleanField(db_index=True, default=False, verbose_name='Port + Refin')),
                ('flag_refin_da_port', models.BooleanField(db_index=True, default=False, verbose_name='Refin da Port')),
            ],
            options={
                'verbose_name': 'Produto (catálogo contratos)',
                'verbose_name_plural': 'Produtos (catálogo contratos)',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddConstraint(
            model_name='banco',
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower('titulo'),
                name='uniq_banco_titulo_lower',
            ),
        ),
        migrations.AddIndex(
            model_name='banco',
            index=models.Index(django.db.models.functions.Lower('titulo'), name='idx_banco_titulo_lower'),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower('titulo'),
                name='uniq_convenio_titulo_lower',
            ),
        ),
        migrations.AddIndex(
            model_name='convenio',
            index=models.Index(django.db.models.functions.Lower('titulo'), name='idx_convenio_titulo_lower'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower('titulo'),
                name='uniq_produto_titulo_lower',
            ),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(django.db.models.functions.Lower('titulo'), name='idx_produto_titulo_lower'),
        ),
        migrations.CreateModel(
            name='TabelaCms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('classificador_banco', models.CharField(db_index=True, default='M1', max_length=2, verbose_name='Classificador Banco')),
                ('taxa_recebido', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa recebido')),
                ('taxa_repasse', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa repasse')),
                ('taxa_plastico', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa plástico')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_cms', to='contratos_v2.banco', verbose_name='Banco')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_cms', to='contratos_v2.convenio', verbose_name='Convênio')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_cms', to='contratos_v2.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Tabela CMS',
                'verbose_name_plural': 'Tabelas CMS',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogCatalogoContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=20, verbose_name='Ação')),
                ('entidade', models.CharField(db_index=True, max_length=20, verbose_name='Entidade')),
                ('registro_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID do registro')),
                ('registro_titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título / identificador')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/hora')),
                ('dados_antes', models.JSONField(blank=True, null=True, verbose_name='Dados antes')),
                ('dados_depois', models.JSONField(blank=True, null=True, verbose_name='Dados depois')),
                ('resumo', models.TextField(blank=True, default='', verbose_name='Resumo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_catalogo_contratos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log catálogo contratos',
                'verbose_name_plural': 'Logs catálogo contratos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail secundário')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('telefone_residencial', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone residencial')),
                ('cliente_dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — contato',
                'verbose_name_plural': 'Cliente — contatos',
            },
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('cliente_dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — endereço',
                'verbose_name_plural': 'Cliente — endereços',
            },
        ),
        migrations.CreateModel(
            name='ClienteRepresentante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome representante')),
                ('cpf_representante', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF representante')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — representante',
                'verbose_name_plural': 'Cliente — representantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo (extensão)')),
                ('arquivo', models.FileField(upload_to='contratos/cliente_arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — arquivo',
                'verbose_name_plural': 'Cliente — arquivos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContatoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=20, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_dinamicos', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — contato (dinâmico)',
                'verbose_name_plural': 'Cliente — contatos (dinâmicos)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteEnderecoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('principal', models.BooleanField(db_index=True, default=False, verbose_name='Endereço principal')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_dinamicos', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
            ],
            options={
                'verbose_name': 'Cliente — endereço (dinâmico)',
                'verbose_name_plural': 'Cliente — endereços (dinâmicos)',
                'ordering': ['-principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Título')),
                ('dados', models.JSONField(blank=True, null=True, verbose_name='Dados da simulação')),
                ('data_criacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='contratos_v2.clientedadospessoais', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacoes_contratos_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Simulação (contratos)',
                'verbose_name_plural': 'Simulações (contratos)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPropostaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(db_index=True, default='ENVIADA', max_length=40, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('observacao_resposta', models.TextField(blank=True, null=True, verbose_name='Observação do retorno (operacional)')),
                ('carteira_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_proposta_contrato', to='siape.carteiraclientes', verbose_name='Carteira')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_proposta', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_proposta_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (vendedor)')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_proposta_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por (operacional)')),
            ],
            options={
                'verbose_name': 'Solicitação de proposta (cliente)',
                'verbose_name_plural': 'Solicitações de proposta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacaopropostacliente',
            index=models.Index(fields=['carteira_clientes', '-data_criacao'], name='c_sp_ix_carteira'),
        ),
        migrations.AddIndex(
            model_name='solicitacaopropostacliente',
            index=models.Index(fields=['estado'], name='c_sp_ix_estado'),
        ),
        migrations.CreateModel(
            name='HistoricoEventoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=40, verbose_name='Estado anterior')),
                ('estado_novo', models.CharField(max_length=40, verbose_name='Estado novo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_eventos', to='contratos_v2.solicitacaopropostacliente', verbose_name='Solicitação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_evento_simulacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de evento (simulação)',
                'verbose_name_plural': 'Históricos de eventos (simulação)',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PropostaDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='Código (token)')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor parcela')),
                ('prazo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo')),
                ('coeficiente', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Coeficiente')),
                ('valor_af', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor AF')),
                ('valor_tc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor TC')),
                ('valor_liberado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor liberado')),
                ('valor_saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor saldo')),
                ('aceita_pelo_cliente', models.BooleanField(default=False, verbose_name='Aceita pelo cliente')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_dados', to='contratos_v2.banco', verbose_name='Banco')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_dados', to='contratos_v2.clientedadospessoais', verbose_name='Cliente')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_dados', to='contratos_v2.convenio', verbose_name='Convênio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_dados_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas_dados', to='contratos_v2.produto', verbose_name='Produto')),
                ('proposta_vinculo_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_refin_geradas', to='contratos_v2.propostadados', verbose_name='Proposta PORT (origem)')),
                ('solicitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_geradas', to='contratos_v2.solicitacaopropostacliente', verbose_name='Solicitação de origem')),
                ('tabela_cms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propostas_dados', to='contratos_v2.tabelacms', verbose_name='Tabela CMS')),
            ],
            options={
                'verbose_name': 'Proposta (dados)',
                'verbose_name_plural': 'Propostas (dados)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('numero_contrato_banco_pre', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nº contrato (banco) — pré-geração')),
                ('link_formalizacao_pre', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link formalização — pré-geração')),
                ('arquivo_pdf_proposta', models.FileField(blank=True, null=True, upload_to='contratos/solicitacoes_digitacao/%Y/%m/', verbose_name='PDF da proposta enviada ao cliente')),
                ('estado', models.CharField(db_index=True, default='PENDENTE_OPERACIONAL', max_length=40, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('carteira_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_digitacao', to='siape.carteiraclientes', verbose_name='Carteira')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_digitacao_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('proposta_dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_digitacao', to='contratos_v2.propostadados', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Solicitação de digitação',
                'verbose_name_plural': 'Solicitações de digitação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEventoDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=40, verbose_name='Estado anterior')),
                ('estado_novo', models.CharField(max_length=40, verbose_name='Estado novo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_eventos', to='contratos_v2.solicitacaodigitacao', verbose_name='Solicitação de digitação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_evento_digitacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de evento (digitação)',
                'verbose_name_plural': 'Históricos de eventos (digitação)',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='ContratoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Nº Contrato')),
                ('fase', models.CharField(db_index=True, default='DIGITACAO_AGUARDANDO', max_length=40, verbose_name='Fase / tabulação operacional (legado, sincronizada)')),
                ('etapa_operacional', models.CharField(db_index=True, default='DIGITACAO', max_length=20, verbose_name='Etapa operacional (nexos)')),
                ('sub_status_operacional', models.CharField(db_index=True, default='DIG_AGUARDANDO', max_length=40, verbose_name='Sub-status operacional')),
                ('portabilidade', models.BooleanField(db_index=True, default=False, verbose_name='Portabilidade (CIP/Refin manual)')),
                ('nivel_risco_checagem_supervisor', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('ALTO', 'Alto')], db_index=True, max_length=10, null=True, verbose_name='Nível de risco (checagem supervisor)')),
                ('observacao_checagem_consultor', models.TextField(blank=True, null=True, verbose_name='Observação do consultor para checagem (+OBS)')),
                ('pendencia_etapa_origem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pendência — etapa de origem')),
                ('pendencia_sub_origem', models.CharField(blank=True, max_length=40, null=True, verbose_name='Pendência — sub-status de origem')),
                ('tag_financeira', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Tag financeira (referência)')),
                ('destaque_vendedor', models.BooleanField(db_index=True, default=False, verbose_name='Destacar para vendedor (ex.: piscar vermelho)')),
                ('link_formalizacao', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de formalização')),
                ('video_cliente', models.FileField(blank=True, null=True, upload_to='contratos/videos/%Y/%m/', verbose_name='Vídeo do cliente')),
                ('video_tamanho', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do vídeo (bytes)')),
                ('flag_video_enviado', models.BooleanField(default=False, verbose_name='Vídeo de conscientização enviado')),
                ('data_criacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Última atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('carteira_clientes_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_execucao_snapshot_carteira', to='siape.carteiraclientes', verbose_name='Carteira (snapshot no fechamento)')),
                ('cliente_dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_execucao', to='contratos_v2.clientedadospessoais', verbose_name='Cliente')),
                ('contrato_vinculo_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_refin_gerados', to='contratos_v2.contratoexecucao', verbose_name='Contrato PORT (origem)')),
                ('proposta_dados', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_execucao', to='contratos_v2.propostadados', verbose_name='Proposta')),
                ('simulacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='contratos_v2.simulacao', verbose_name='Simulação (origem)')),
                ('solicitacao_digitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_execucao', to='contratos_v2.solicitacaodigitacao', verbose_name='Solicitação de digitação')),
                ('user_repasse_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_execucao_como_repasse_snapshot', to=settings.AUTH_USER_MODEL, verbose_name='Usuário repasse (snapshot)')),
            ],
            options={
                'verbose_name': 'Contrato (execução)',
                'verbose_name_plural': 'Contratos (execução)',
                'ordering': ['-data_ultima_atualizacao'],
            },
        ),
        migrations.AddIndex(
            model_name='contratoexecucao',
            index=models.Index(fields=['fase', 'destaque_vendedor'], name='c_sp_ix_fase_dest'),
        ),
        migrations.AddIndex(
            model_name='contratoexecucao',
            index=models.Index(fields=['etapa_operacional', 'sub_status_operacional']),
        ),
        migrations.AddIndex(
            model_name='contratoexecucao',
            index=models.Index(fields=['contrato_vinculo_port'], name='idx_ce_vinculo_port'),
        ),
        migrations.CreateModel(
            name='ContratoPortado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(blank=True, max_length=80, null=True, verbose_name='Número do contrato')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor parcela')),
                ('valor_af', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor AF')),
                ('valor_devedor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor devedor total')),
                ('prazo_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo total')),
                ('prazo_restante', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo restante')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_portados', to='contratos_v2.banco', verbose_name='Banco (origem)')),
                ('contrato_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_portados_origem', to='contratos_v2.contratoexecucao', verbose_name='Contrato digitado (quando existir)')),
                ('proposta_dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_portados', to='contratos_v2.propostadados', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Contrato existente (portado)',
                'verbose_name_plural': 'Contratos existentes (portados)',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ClienteBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=120, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('dv_agencia', models.CharField(blank=True, max_length=5, null=True, verbose_name='DV agência')),
                ('conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta')),
                ('dv_conta', models.CharField(blank=True, max_length=5, null=True, verbose_name='DV conta')),
                ('tipo_conta', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de conta')),
                ('tipo_pagamento', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de pagamento')),
                ('incluir_seguro', models.BooleanField(default=False, verbose_name='Incluir seguro')),
                ('matricula', models.CharField(blank=True, max_length=80, null=True, verbose_name='Matrícula')),
                ('senha', models.CharField(blank=True, max_length=120, null=True, verbose_name='Senha (evitar texto puro em produção)')),
                ('cliente_dados_pessoais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bancario', to='contratos_v2.clientedadospessoais', verbose_name='Dados pessoais')),
                ('contrato_execucao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_bancarios', to='contratos_v2.contratoexecucao', verbose_name='Contrato (se gerado)')),
                ('proposta_dados', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='contratos_v2.propostadados', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Cliente — dados bancários',
                'verbose_name_plural': 'Cliente — dados bancários',
            },
        ),
        migrations.CreateModel(
            name='ContratoDadosOperacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor parcela')),
                ('prazo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo')),
                ('valor_af', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor AF')),
                ('valor_tc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor TC')),
                ('valor_liberado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor liberado')),
                ('valor_saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor saldo (snapshot)')),
                ('tabela_cms_titulo_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='Título da tabela CMS (snapshot)')),
                ('taxa_recebido_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa recebido (snapshot)')),
                ('taxa_repasse_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa repasse (snapshot)')),
                ('taxa_plastico_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taxa plástico (snapshot)')),
                ('data_att_cms', models.DateTimeField(blank=True, null=True, verbose_name='Última alteração manual dos percentuais (CMS)')),
                ('percentual_af_manual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Percentual manual sobre AF (financeiro)')),
                ('valor_af_base_cms', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='AF base para cálculo CMS (financeiro)')),
                ('classificador_banco_operacional', models.CharField(blank=True, max_length=2, null=True, verbose_name='Classificador banco (override financeiro)')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_v2.banco', verbose_name='Banco')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_v2.convenio', verbose_name='Convênio')),
                ('contrato_execucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_operacionais', to='contratos_v2.contratoexecucao', verbose_name='Contrato')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_v2.produto', verbose_name='Produto')),
                ('tabela_cms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos_v2.tabelacms', verbose_name='Tabela CMS')),
                ('user_att_cms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_cms_snapshot_editados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da última alteração CMS (contrato)')),
            ],
            options={
                'verbose_name': 'Contrato — dados operacionais',
                'verbose_name_plural': 'Contratos — dados operacionais',
            },
        ),
        migrations.CreateModel(
            name='HistoricoTransicaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(blank=True, default='', max_length=20, verbose_name='Etapa anterior')),
                ('sub_anterior', models.CharField(blank=True, default='', max_length=40, verbose_name='Sub anterior')),
                ('etapa_nova', models.CharField(max_length=20, verbose_name='Etapa nova')),
                ('sub_nova', models.CharField(max_length=40, verbose_name='Sub nova')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('contrato_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transicoes', to='contratos_v2.contratoexecucao', verbose_name='Contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_transicao_contrato', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de transição (contrato)',
                'verbose_name_plural': 'Históricos de transição (contratos)',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TagStatusOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=40, verbose_name='Tag')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('carteira_clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_status_operacional', to='siape.carteiraclientes', verbose_name='Carteira')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_status_operacional_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tag status operacional',
                'verbose_name_plural': 'Tags status operacional',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=20, verbose_name='Tipo')),
                ('observacao', models.TextField(verbose_name='Observação (obrigatória)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolvido', models.BooleanField(db_index=True, default=False, verbose_name='Resolvido')),
                ('contrato_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='contratos_v2.contratoexecucao', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
            ],
            options={
                'verbose_name': 'Pendência (contrato)',
                'verbose_name_plural': 'Pendências (contratos)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pendencia',
            index=models.Index(fields=['contrato_execucao', 'resolvido']),
        ),
        migrations.AddIndex(
            model_name='pendencia',
            index=models.Index(fields=['tipo', 'resolvido']),
        ),
        migrations.CreateModel(
            name='EnvioComprovantePagamentoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='contratos/comprovantes_pagamento_vendedor/%Y/%m/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('contrato_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_comprovante_pagamento_vendedor', to='contratos_v2.contratoexecucao', verbose_name='Contrato')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_comprovante_pagamento_contrato', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Envio de comprovante (vendedor)',
                'verbose_name_plural': 'Envios de comprovantes (vendedor)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='enviocomprovantepagamentovendedor',
            index=models.Index(fields=['contrato_execucao', '-criado_em']),
        ),
        migrations.CreateModel(
            name='ComprovanteTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor pago (TC)')),
                ('arquivo', models.FileField(upload_to='contratos/comprovantes_tc/%Y/%m/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contrato_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_tc', to='contratos_v2.contratoexecucao', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_tc_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Comprovante TC',
                'verbose_name_plural': 'Comprovantes TC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
