# Generated by Django 6.0 on 2026-01-05 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Banco')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Convênio')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Operação')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TabulacaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tabulação')),
                ('ordem', models.IntegerField(help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor em hexadecimal (ex: #6c757d)', max_length=7, verbose_name='Cor')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tabulação de Contrato',
                'verbose_name_plural': 'Tabulações de Contrato',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('VENDEDOR_CONSULTOR', 'Vendedor/Consultor'), ('ADMIN', 'Administrador')], max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuário',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContratoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_contrato', models.JSONField(help_text='Campos comuns + customizados em formato JSON', verbose_name='Dados do Contrato')),
                ('link_formalizacao', models.TextField(blank=True, null=True, verbose_name='Link de Formalização')),
                ('cliente_formalizou', models.BooleanField(default=False, verbose_name='Cliente Formalizou')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_formalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Formalização')),
                ('data_liberacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Liberação')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.banco', verbose_name='Banco')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Contrato Operacional',
                'verbose_name_plural': 'Contratos Operacionais',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('tipo_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.contratooperacional', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Anexo de Contrato',
                'verbose_name_plural': 'Anexos de Contrato',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='BancoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('data_ativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios_associados', to='contratos.banco', verbose_name='Banco')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos_associados', to='contratos.convenio', verbose_name='Convênio')),
            ],
            options={
                'verbose_name': 'Associação Banco-Convênio',
                'verbose_name_plural': 'Associações Banco-Convênio',
                'ordering': ['banco__nome', 'convenio__nome'],
                'unique_together': {('banco', 'convenio')},
            },
        ),
        migrations.CreateModel(
            name='ConvenioOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('data_ativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_associadas', to='contratos.convenio', verbose_name='Convênio')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios_associados', to='contratos.operacao', verbose_name='Operação')),
            ],
            options={
                'verbose_name': 'Associação Convênio-Operação',
                'verbose_name_plural': 'Associações Convênio-Operação',
                'ordering': ['convenio__nome', 'operacao__nome'],
                'unique_together': {('convenio', 'operacao')},
            },
        ),
        migrations.AddField(
            model_name='contratooperacional',
            name='convenio_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.conveniooperacao', verbose_name='Convênio+Operação'),
        ),
        migrations.CreateModel(
            name='SchemaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número Inteiro'), ('DECIMAL', 'Número Decimal'), ('EMAIL', 'Email'), ('TEL', 'Telefone'), ('DATE', 'Data'), ('TEXTAREA', 'Área de Texto'), ('SELECT', 'Seleção Única'), ('CHECKBOX', 'Checkbox'), ('PASSWORD', 'Senha'), ('MULTISELECTOR', 'Seleção Múltipla'), ('MULTIINPUT', 'Múltiplos Inputs')], max_length=20, verbose_name='Tipo')),
                ('choices', models.JSONField(blank=True, help_text='Array de strings para SELECT e MULTISELECTOR', null=True, verbose_name='Opções')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('convenio_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_schema', to='contratos.conveniooperacao', verbose_name='Convênio+Operação')),
            ],
            options={
                'verbose_name': 'Campo de Schema',
                'verbose_name_plural': 'Campos de Schema',
                'ordering': ['convenio_operacao', 'ordem', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TabelaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela', models.CharField(max_length=255, verbose_name='Nome da Tabela')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('banco_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_comissao', to='contratos.bancoconvenio', verbose_name='Banco+Convênio')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_comissao', to='contratos.operacao', verbose_name='Operação')),
            ],
            options={
                'verbose_name': 'Tabela de Comissão',
                'verbose_name_plural': 'Tabelas de Comissão',
                'ordering': ['banco_convenio', 'nome_tabela'],
            },
        ),
        migrations.CreateModel(
            name='RegraComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regra', models.CharField(choices=[('A_PRAZO', 'A Prazo'), ('A_VISTA', 'À Vista'), ('VALOR_FIXO', 'Valor Fixo')], max_length=20, verbose_name='Tipo de Regra')),
                ('prazo', models.IntegerField(blank=True, null=True, verbose_name='Prazo')),
                ('vigencia_inicio', models.DateField(verbose_name='Vigência Início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência Fim')),
                ('coeficiente', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Coeficiente')),
                ('outros_recebimentos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Outros Recebimentos (%)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('flat_recebida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Flat Recebida (%)')),
                ('bonus_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bônus Recebido (%)')),
                ('adiantamento_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adiantamento Recebido (%)')),
                ('total_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Recebido (%)')),
                ('flat_repassada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Flat Repassada (%)')),
                ('bonus_repassado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bônus Repassado (%)')),
                ('adiantamento_repassado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adiantamento Repassado (%)')),
                ('total_repassado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Repassado (%)')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recebido (R$)')),
                ('valor_repassado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Repassado (R$)')),
                ('regras', models.JSONField(blank=True, help_text='Lista de regras com nome, valor_min, valor_max, tipo_regra', null=True, verbose_name='Regras')),
                ('tabela_comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='contratos.tabelacomissao', verbose_name='Tabela de Comissão')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
                'ordering': ['tabela_comissao', 'tipo_regra'],
            },
        ),
        migrations.AddField(
            model_name='contratooperacional',
            name='status_tabulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.tabulacaocontrato', verbose_name='Tabulação'),
        ),
        migrations.AddIndex(
            model_name='contratooperacional',
            index=models.Index(fields=['vendedor', 'status_tabulacao'], name='contratos_c_vendedo_557093_idx'),
        ),
        migrations.AddIndex(
            model_name='contratooperacional',
            index=models.Index(fields=['status_tabulacao', 'data_criacao'], name='contratos_c_status__e1eff3_idx'),
        ),
    ]
