# Generated by Django 6.0 on 2026-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniooperacao',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título descritivo para este schema', max_length=255, null=True, verbose_name='Título do Schema'),
        ),
    ]
