# Generated by Django 6.0 on 2026-01-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_conveniooperacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacampo',
            name='choices',
            field=models.JSONField(blank=True, help_text='Array de strings para SELECT, MULTISELECTOR, FILE e MULTIFILE', null=True, verbose_name='Opções'),
        ),
        migrations.AlterField(
            model_name='schemacampo',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número Inteiro'), ('DECIMAL', 'Número Decimal'), ('EMAIL', 'Email'), ('TEL', 'Telefone'), ('DATE', 'Data'), ('TEXTAREA', 'Área de Texto'), ('SELECT', 'Seleção Única'), ('CHECKBOX', 'Checkbox'), ('PASSWORD', 'Senha'), ('MULTISELECTOR', 'Seleção Múltipla (Dropdown)'), ('MULTIINPUT', 'Múltiplos Inputs'), ('FILE', 'Upload de Arquivo Único'), ('MULTIFILE', 'Upload de Múltiplos Arquivos')], max_length=20, verbose_name='Tipo'),
        ),
    ]
