# Generated by Django 6.0 on 2026-01-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_schemacampo_choices_alter_schemacampo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conveniooperacao',
            options={'ordering': ['convenio__nome', 'operacao__nome', 'titulo'], 'verbose_name': 'Schema (Convênio-Operação)', 'verbose_name_plural': 'Schemas (Convênio-Operação)'},
        ),
        migrations.AlterUniqueTogether(
            name='conveniooperacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conveniooperacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='conveniooperacao',
            name='data_ativacao',
        ),
        migrations.CreateModel(
            name='BancoConvenioOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_ativacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas_ativos', to='contratos.banco', verbose_name='Banco')),
                ('convenio_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos_ativos', to='contratos.conveniooperacao', verbose_name='Schema (Convênio+Operação)')),
            ],
            options={
                'verbose_name': 'Ativação de Schema por Banco',
                'verbose_name_plural': 'Ativações de Schema por Banco',
                'ordering': ['banco__nome', 'convenio_operacao__convenio__nome', 'convenio_operacao__operacao__nome'],
                'unique_together': {('banco', 'convenio_operacao')},
            },
        ),
    ]
