# Generated by Django - Adicionando sistema de páginas para schemas
from django.db import migrations, models


def set_dados_existentes(apps, schema_editor):
    """
    Garante que dados existentes não quebrem:
    - SchemaCampo: define pagina=1 para registros existentes
    - ContratoOperacional: marca como NÃO rascunho (já foram enviados)
    """
    SchemaCampo = apps.get_model('contratos', 'SchemaCampo')
    ContratoOperacional = apps.get_model('contratos', 'ContratoOperacional')
    
    # SchemaCampo: definir pagina=1 para registros existentes
    SchemaCampo.objects.all().update(pagina=1)
    
    # ContratoOperacional: marcar contratos existentes como NÃO rascunho
    # pagina_atual=0 indica que o contrato está completo
    ContratoOperacional.objects.all().update(is_rascunho=False, pagina_atual=0)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_conveniooperacao_options_and_more'),
    ]

    operations = [
        # Adicionar campo 'pagina' ao SchemaCampo
        migrations.AddField(
            model_name='schemacampo',
            name='pagina',
            field=models.IntegerField(default=1, help_text='Número da página no formulário (mínimo 1)', verbose_name='Página'),
        ),
        # Adicionar campo 'is_rascunho' ao ContratoOperacional
        migrations.AddField(
            model_name='contratooperacional',
            name='is_rascunho',
            field=models.BooleanField(default=True, help_text='True se o contrato ainda não foi totalmente preenchido', verbose_name='É Rascunho'),
        ),
        # Adicionar campo 'pagina_atual' ao ContratoOperacional
        migrations.AddField(
            model_name='contratooperacional',
            name='pagina_atual',
            field=models.IntegerField(default=1, help_text='Página atual do formulário (0 = completo)', verbose_name='Página Atual'),
        ),
        # Adicionar índice para is_rascunho (performance em queries)
        migrations.AddIndex(
            model_name='contratooperacional',
            index=models.Index(fields=['is_rascunho'], name='contratos_c_is_rasc_8d7f4e_idx'),
        ),
        # RunPython para garantir dados existentes
        migrations.RunPython(set_dados_existentes, migrations.RunPython.noop),
    ]
