# Generated by Django 6.0 on 2026-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contratooperacional_numero_serie'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contratooperacional',
            name='contratos_c_is_rasc_8d7f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='contratooperacional',
            new_name='contratos_c_numero__bc3eb5_idx',
            old_name='contratos_c_numero__idx',
        ),
    ]
