# Generated by Django 6.0 on 2025-12-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh_admin', '0001_initial'),
        ('siape', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de 0 a 100', max_digits=5, verbose_name='Percentual (%)')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Classificador',
                'verbose_name_plural': 'Classificadores',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ContratoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_cpf', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('banco', models.CharField(max_length=255, verbose_name='Banco')),
                ('valor_af', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor AF (R$)')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Repasse (R$)')),
                ('flg_ponta', models.BooleanField(default=False, help_text='Marcado se NÃO for contrato novo/ponta', verbose_name='Ponta')),
                ('data_contrato', models.DateField(verbose_name='Data do Contrato')),
                ('status', models.CharField(choices=[('A_PAGAR', 'A Pagar'), ('PAGO', 'Pago'), ('NAO_PAGO', 'Não Pago')], default='A_PAGAR', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('classificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pagamento', to='financeiro_vendas.classificador', verbose_name='Classificador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pagamento', to='siape.produto', verbose_name='Produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pagamento', to='rh_admin.setor', verbose_name='Setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Contrato de Pagamento',
                'verbose_name_plural': 'Contratos de Pagamento',
                'ordering': ['-data_contrato', '-data_criacao'],
                'indexes': [models.Index(fields=['cliente_cpf'], name='financeiro__cliente_64e4f0_idx'), models.Index(fields=['status', 'status_ativo'], name='financeiro__status_483975_idx'), models.Index(fields=['user', 'status'], name='financeiro__user_id_958b6e_idx')],
            },
        ),
    ]
