# Generated by Django 6.0 on 2025-12-17 19:52

import apps.vendas.siape.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Campanha')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TabulacaoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tabulação')),
                ('ordem', models.IntegerField(help_text='Ordem de exibição no CRM (menor número aparece primeiro)', verbose_name='Ordem')),
                ('cor', models.CharField(default='#6c757d', help_text='Cor em hexadecimal (ex: #6c757d)', max_length=7, verbose_name='Cor')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tabulação CRM',
                'verbose_name_plural': 'Tabulações CRM',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_base', models.CharField(blank=True, choices=[('PENSIONISTA', 'Pensionista'), ('SERVIDOR', 'Servidor')], max_length=20, null=True, verbose_name='Tipo de Base')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('situacao_funcional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Funcional')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['cpf'], name='siape_clien_cpf_9c127c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ControleCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('data_contato', models.DateField(verbose_name='Data de Contato')),
                ('hora_contato', models.TimeField(verbose_name='Hora de Contato')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_crm', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('tabulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='siape.tabulacaocrm', verbose_name='Tabulação')),
            ],
            options={
                'verbose_name': 'Controle CRM',
                'verbose_name_plural': 'Controles CRM',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DadosChecagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_para_checagem', models.DateField(verbose_name='Data para Checagem')),
                ('horario_disponivel', models.TimeField(verbose_name='Horário Disponível')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('nome_banco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Banco')),
                ('valor_af', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor AF (R$)')),
                ('valor_repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Repasse (R$)')),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Devedor (R$)')),
                ('valor_parcela_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Parcela Atual (R$)')),
                ('valor_parcela_nova_proposta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Parcela Nova Proposta (R$)')),
                ('valor_troco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Troco (R$)')),
                ('prazo_atual', models.IntegerField(blank=True, null=True, verbose_name='Prazo Atual (meses)')),
                ('prazo_acordado', models.IntegerField(blank=True, null=True, verbose_name='Prazo Acordado (meses)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('controle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_checagem', to='siape.controlecrm', verbose_name='Controle CRM')),
                ('responsavel_por_checagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checagens_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável por Checagem')),
            ],
            options={
                'verbose_name': 'Dados de Checagem',
                'verbose_name_plural': 'Dados de Checagens',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoChecagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.vendas.siape.models.get_crm_upload_path, verbose_name='Arquivo')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('checagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='siape.dadoschecagem', verbose_name='Checagem')),
            ],
            options={
                'verbose_name': 'Arquivo de Checagem',
                'verbose_name_plural': 'Arquivos de Checagens',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DadosReversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_para_reversao', models.DateField(verbose_name='Data para Reversão')),
                ('horario_disponivel', models.TimeField(verbose_name='Horário Disponível')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('controle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_reversao', to='siape.controlecrm', verbose_name='Controle CRM')),
                ('responsavel_por_reversao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável por Reversão')),
            ],
            options={
                'verbose_name': 'Dados de Reversão',
                'verbose_name_plural': 'Dados de Reversões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoReversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.vendas.siape.models.get_crm_upload_path, verbose_name='Arquivo')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('reversao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='siape.dadosreversao', verbose_name='Reversão')),
            ],
            options={
                'verbose_name': 'Arquivo de Reversão',
                'verbose_name_plural': 'Arquivos de Reversões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula')),
                ('matricula_instituidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula Instituidor')),
                ('base_calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base de Cálculo')),
                ('orgao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão')),
                ('upag', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPAG')),
                ('rubrica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubrica')),
                ('rjur', models.CharField(blank=True, max_length=50, null=True, verbose_name='RJUR')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='siape.campanha', verbose_name='Campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='siape.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Margens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruta_5', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bruta 5%')),
                ('util_5', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Util 5%')),
                ('saldo_5', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo 5%')),
                ('bruta_5b', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bruta 5B%')),
                ('util_5b', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Util 5B%')),
                ('saldo_5b', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo 5B%')),
                ('bruta_35', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bruta 35%')),
                ('util_35', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Util 35%')),
                ('saldo_35', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo 35%')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margens', to='siape.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Margem',
                'verbose_name_plural': 'Margens',
                'ordering': ['matricula__cliente__nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Contrato')),
                ('contrato', models.CharField(max_length=100, verbose_name='Contrato')),
                ('banco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Parcela')),
                ('parcelas_restantes', models.IntegerField(blank=True, null=True, verbose_name='Parcelas Restantes')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='siape.campanha', verbose_name='Campanha')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='siape.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-matricula__data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MetaSIAPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Meta')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Meta (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Meta SIAPE',
                'verbose_name_plural': 'Metas SIAPE',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['data_inicio', 'data_final'], name='siape_metas_data_in_4ece77_idx'), models.Index(fields=['status'], name='siape_metas_status_a5fbae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REVERSAO', 'Reversão'), ('CHECAGEM', 'Checagem')], max_length=20, verbose_name='Tipo')),
                ('horario_inicio', models.TimeField(blank=True, help_text='Horário de início do atendimento', null=True, verbose_name='Horário Início')),
                ('horario_final', models.TimeField(blank=True, help_text='Horário final do atendimento', null=True, verbose_name='Horário Final')),
                ('tempo_call', models.IntegerField(default=30, help_text='Duração de cada atendimento em minutos', verbose_name='Tempo de Call (minutos)')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuarios', models.ManyToManyField(related_name='representantes', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Responsáveis')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['tipo', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(help_text='Hora:minuto do agendamento', verbose_name='Hora')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('controle_crm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_agendados', to='siape.controlecrm', verbose_name='Controle CRM')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_agendados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('tabulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_agendados', to='siape.tabulacaocrm', verbose_name='Tabulação')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data', 'hora'],
            },
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['matricula'], name='siape_matri_matricu_855e94_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['cliente', 'matricula'], name='siape_matri_cliente_fcfe47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('cliente', 'matricula')},
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['contrato'], name='siape_contr_contrat_0e1f87_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['matricula', 'contrato'], name='siape_contr_matricu_cc5060_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('matricula', 'contrato')},
        ),
        migrations.AddIndex(
            model_name='horariodisponivel',
            index=models.Index(fields=['data', 'hora', 'responsavel'], name='siape_horar_data_2d89b2_idx'),
        ),
        migrations.AddIndex(
            model_name='horariodisponivel',
            index=models.Index(fields=['tabulacao', 'status'], name='siape_horar_tabulac_e96cdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponivel',
            unique_together={('controle_crm', 'data', 'hora', 'responsavel', 'tabulacao')},
        ),
        migrations.AddIndex(
            model_name='controlecrm',
            index=models.Index(fields=['cpf'], name='siape_contr_cpf_8b10db_idx'),
        ),
        migrations.AddIndex(
            model_name='controlecrm',
            index=models.Index(fields=['tabulacao', 'status'], name='siape_contr_tabulac_6e1984_idx'),
        ),
    ]
