# Generated by Django 6.0 on 2025-12-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
    ]
