# Generated by Django 6.0 on 2026-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0002_cliente_celular'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matricula',
            name='siape_matri_cliente_fcfe47_idx',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('cliente', 'campanha', 'matricula')},
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['cliente', 'campanha', 'matricula'], name='siape_matri_cliente_d6b9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['campanha', 'status'], name='siape_matri_campanh_3a9d07_idx'),
        ),
    ]
