# Generated by Django 6.0 on 2026-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0003_remove_matricula_siape_matri_cliente_fcfe47_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contrato',
            name='siape_contr_matricu_cc5060_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_parcela',
            field=models.PositiveIntegerField(default=1, verbose_name='Número da parcela/débito'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('matricula', 'contrato', 'numero_parcela')},
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['matricula', 'contrato', 'numero_parcela'], name='siape_contr_matricu_14de8e_idx'),
        ),
    ]
