# Generated by Django 6.0 on 2025-12-17 19:52

import apps.rh.funcionarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone Boxicons', max_length=50, null=True, verbose_name='Ícone')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Horário')),
                ('entrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('saida_almoco', models.TimeField(verbose_name='Saída para Almoço')),
                ('volta_almoco', models.TimeField(verbose_name='Volta do Almoço')),
                ('saida', models.TimeField(verbose_name='Horário de Saída')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.rh.funcionarios.models.get_funcionario_upload_path, verbose_name='Foto')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pessoa', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Pessoal')),
                ('celular_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Principal')),
                ('celular_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Secundário')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Arquivo')),
                ('arquivo', models.FileField(upload_to=apps.rh.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Arquivo do Funcionário',
                'verbose_name_plural': 'Arquivos dos Funcionários',
                'ordering': ['funcionario__nome_completo', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade (Cidade de Nascimento)')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_pessoais', to='funcionarios.genero', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Dados Pessoais',
                'verbose_name_plural': 'Dados Pessoais',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='DadosProfissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pis', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh_admin.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh_admin.departamento', verbose_name='Departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh_admin.empresa', verbose_name='Empresa')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='rh_admin.equipe', verbose_name='Equipe')),
                ('lojas', models.ManyToManyField(blank=True, related_name='funcionarios', to='rh_admin.loja', verbose_name='Lojas')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh_admin.setor', verbose_name='Setor')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_profissionais', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='funcionarios.horariotrabalho', verbose_name='Horário de Trabalho')),
                ('tipo_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dados_profissionais', to='funcionarios.tipocontrato', verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Dados Profissionais',
                'verbose_name_plural': 'Dados Profissionais',
                'ordering': ['funcionario__nome_completo'],
            },
        ),
    ]
